listening-port=3478
tls-listening-port=5349
min-port=49152
max-port=65535
external-ip=${PUBLIC_IP}
realm=turn.${DOMAIN}
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret=${TURN_SECRET}
no-multicast-peers
no-cli